[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "git"]

[phases.install]
cmd = """
composer install --no-dev --optimize-autoloader
"""

[phases.build]
cmd = """
php artisan config:cache
php artisan route:cache
php artisan migrate --force
"""

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_IGNORE_NODE = "true"
